#!/usr/bin/env python3

import json
import os
import shutil
import sys

with open("config.json") as config_json:
    config = json.load(config_json)

def handle_request(src, dest):

    if "SECONDARY_ARCHIVE" in os.environ:
        archive_path = os.environ["SECONDARY_ARCHIVE"]
    else:
        archive_path= "/tmp"

    if not os.path.exists(src):
        print(src+" doesn't exist")
        sys.exit(1)

    os.makedirs(archive_path+"/"+dest, exist_ok=True)

    print("src:%s dest:%s" % (src, archive_path+"/"+dest))
    recursive_overwrite(src, archive_path+"/"+dest)

def recursive_overwrite(src, dest, ignore=None):
    if os.path.isdir(src):
        if not os.path.isdir(dest):
            os.makedirs(dest)
        files = os.listdir(src)
        if ignore is not None:
            ignored = ignore(src, files)
        else:
            ignored = set()
        for f in files:
            if f not in ignored:
                recursive_overwrite(os.path.join(src, f),
                                    os.path.join(dest, f),
                                    ignore)
    else:
        shutil.copyfile(src, dest)

#deprecated by requests
if "validator_task" in config:
    dtv_task_id = config["validator_task"]["_id"]
    follow_task_id = config["validator_task"]["deps_config"][0]["task"]
    group_id = str(config["validator_task"]["_group_id"])
    instance_id = config["validator_task"]["instance_id"]
    output_id = config["validator_task"]["config"]["_outputs"][0]["id"]

    src = "../"+dtv_task_id+"/secondary"
    dest=group_id+"/"+instance_id+"/"+follow_task_id+"/"+output_id+"/secondary"

    handle_request(src, dest)

if "requests" in config:
    for request in config["requests"]:
        src = request["src"]
        src += "/secondary"

        dest = ""
        dest += str(request["group_id"])
        dest += "/"+request["instance_id"]
        dest += "/"+request["task_id"]
        dest += "/"+request["subdir"]
        dest += "/secondary"

        #if "path" in request:
        #    src += "/"+request["path"]
        #    dest += "/"+request["path"]

        handle_request(src, dest)



